In [3]:
import numpy as np
import pandas as pd

In [15]:
# load data
label_pathe = r"D:\BrownUnivercity\CS2470\final_proj\motion_to_melody\data\EMOPIA_1.0\label.csv"
label = pd.read_csv(label_pathe)
# songs name ; emotion label ; who label

                    ID  4Q annotator
0     Q1_0vLPYiPN7qY_0   1         D
1     Q1_0vLPYiPN7qY_1   1         D
2     Q1_0vLPYiPN7qY_2   1         D
3     Q1_1Qc15G0ZHIg_1   1         D
4     Q1_1Qc15G0ZHIg_2   1         D
...                ...  ..       ...
1073  Q4_xgtwQGeB6_0_0   4         C
1074  Q4_xrhWli_R98g_0   4         C
1075  Q4_xrhWli_R98g_2   4         C
1076  Q4_yC0fAQxGgr0_0   4         C
1077  Q4_yC0fAQxGgr0_1   4         C

[1078 rows x 3 columns]


In [5]:
import numpy as np

result_array = [[1,2,3],
              [4,5,6],
              [7,8,9]]

if len(result_array) > 5:
    result_array = result_array[:20000]
else:
    num_to_pad = 5 - len(result_array)
    result_array = np.pad(result_array, ((0, num_to_pad), (0, 0)), mode='constant')

print(result_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]
 [0 0 0]]
